package de.gurkengewuerz.twitchbotr2.gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by gurkengewuerz.de on 18.12.2016.
 */
public class DashboardGUI {
    private JPanel mainPane;
    private JTabbedPane paneSites;
    private JPanel configPane;
    private JPanel consolePane;
    private JPanel userDatabasePane;
    private JPanel commandsPane;
    private JPanel musicPane;
    private JPanel dashboardPane;
    private JPanel giveawayPane;
    private JButton DEBUGButton;

    public DashboardGUI() {
        JFrame frame = new JFrame("DashboardGUI");
        frame.setContentPane(mainPane);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

        DEBUGButton.addActionListener(e -> {
            System.out.println(mainPane.getSize());
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        paneSites = new JTabbedPane();
        mainPane.add(paneSites, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(875, 415), null, 0, false));
        configPane = new JPanel();
        configPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        paneSites.addTab("Config", configPane);
        DEBUGButton = new JButton();
        DEBUGButton.setText("DEBUG");
        DEBUGButton.setToolTipText("Debug Tools");
        configPane.add(DEBUGButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        consolePane = new JPanel();
        consolePane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        paneSites.addTab("Console", consolePane);
        dashboardPane = new JPanel();
        dashboardPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        paneSites.addTab("Dashboard", dashboardPane);
        userDatabasePane = new JPanel();
        userDatabasePane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        paneSites.addTab("User Database", userDatabasePane);
        commandsPane = new JPanel();
        commandsPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        paneSites.addTab("Commands", commandsPane);
        musicPane = new JPanel();
        musicPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        paneSites.addTab("Music", musicPane);
        giveawayPane = new JPanel();
        giveawayPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        paneSites.addTab("Giveaway", giveawayPane);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }
}
